// <auto-generated />
namespace DiplomaDataModel.Migration.Record
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initRecords : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initRecords));
        
        string IMigrationMetadata.Id
        {
            get { return "201511120427402_initRecords"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
